### ISSUE TITLE
SQLAlchemyMiddleware does not return response

### ISSUE THREAD

**Issue by esquonk** [shosca/django-sorcery#142]
`SQLAlchemyMiddleware` does not return response object and breaks middleware chain
```
        finally:
            self.return_response(request, response)
```

[This commit](https://github.com/shosca/django-sorcery/commit/12c2163f4e011a1f20e0005b190f921be3fec4ad#diff-8d9b37a3ac7eb23afe3b6811f4c57dcc) appears to cause the issue.

Am I missing something here?

**Comment by esquonk** [comment]
I get the following error when I put `django_sorcery.db.middleware.SQLAlchemyMiddleware` at the top of `MIDDLEWARE` list.

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Users\mi\proj\venv\flights\lib\site-packages\django\contrib\staticfiles\handlers.py", line 65, in __call__
    return self.application(environ, start_response)
  File "C:\Users\mi\proj\venv\flights\lib\site-packages\django\core\handlers\wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "C:\Users\mi\proj\venv\flights\lib\site-packages\django\core\handlers\base.py", line 76, in get_response
    response._closable_objects.append(request)
AttributeError: 'NoneType' object has no attribute '_closable_objects'
```

**Comment by shosca** [comment]
You're correct, it should return response there

**Comment by shosca** [comment]
Please try the fix. You can install it with `pip install https://github.com/shosca/django-sorcery/archive/middleware.zip`

**Comment by esquonk** [comment]
Thanks for the quick fix!
